# Generated by Django 3.1.7 on 2021-05-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_num', models.IntegerField(unique=True)),
                ('ac_type', models.CharField(choices=[('Current account', 'Current account'), ('Savings account', 'Savings account '), ('NRI accounts', 'NRI accounts')], default='Current account', max_length=120)),
                ('balance', models.IntegerField()),
                ('user', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_ac_num', models.CharField(max_length=40)),
                ('amount', models.IntegerField()),
                ('debit_credit', models.CharField(choices=[('Debited', 'Debited'), ('Credited', 'Credited')], default='Credited', max_length=20)),
                ('transaction_date', models.DateField(auto_now=True)),
                ('from_ac_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.accounts')),
            ],
        ),
    ]
